pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'build start'
                sh 'mvn --version'
                echo 'build end'
            }
        }
        stage('Test') {
            steps {
                //
                echo 'Test start'
                echo 'Test end'
            }
        }
        stage('Deploy') {
            steps {
                //
                echo 'Deploy start'
                echo 'Deploy end'
            }
        }
    }
}